name: Despliega la web a GitHub Pages
on:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CI: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Configura Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - name: Configura Pages
        uses: actions/configure-pages@v2
      - name: Instala las dependencias
        run: npm ci
      - name: Construye la web
        run: npm run build
      - name: Carga la web construida
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Despliega en GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1